// export const questions = [
//   "Should couples keep secrets?",
//   "Is jealousy healthy in a relationship?",
//   "Who do you think is more attractive- me or you?",
//   "Describe how you are in bed in 3 words.",
//   "If someone offered you a million dollars to leave me tonight, would you take it?",
//   "Would you date someone who's ugly?",
//   "Do you think your parents would approve if you and your partner got married?",
//   "When was the first moment that you knew that you were attracted to me — and what was it that first attracted you to me",
//   "Change is a natural part of life, so what is it that has changed about me since we got together, and is it something you like?",
//   "When we are in an argument or a serious discussion, do you ever just go ahead and apologize, not because you feel you are wrong, but because you just want the argument to end?",
//   "We all have an ideal or dream partner. Do I give you everything, or almost everything, that you want or are searching for in a partner?",
//   "If we had never gotten together, where do you think you’d be and how do you think your life would be right now?",
//   "We all have relationship deal breakers, so what’s the one thing that would make you end our relationship?",
//   "What is your absolute favorite thing for us to do together? And why that? ",
//   "Would you ever want me to have cosmetic surgery or plastic surgery, and on what part of my body and why?",
//   "Two lies and a truth",
//   "Is your browsing history on your mobile phone something that you’d let me look at? Why or why not?",
//   "Would you rather lose your sex organs or gain 100 pounds?",
//   "Did you ever fart inside an elevator?",
//   "What’s your biggest turn off in a person of the opposite sex?",
//   "Do you like my (your partner’s) cooking?",
//   "What is your idea of a perfect couples’ holiday?",
//   "Would you ever want to undergo plastic surgery? Why?",
//   "How would you spend an entire week without me?",
//   "Which is your favorite color on me?",
//   "Is there something that you love a lot, but you sacrificed just for me?",
//   "What is one household chore that you hate to do?",
//   "Were you ever on a blind date (not thru dating apps)?",
//   "Which animal comes to your mind when you think of me?",
//   "Rate the style of my dressing on a scale of 1 to 10.",
//   "Name one thing that you just can’t give up even for me.",
//   "What is your idea of a perfect marriage?",
//   "Which of my friends do you like to talk to?",
//   "Which is the most embarrassing show you are guilty of watching?",
//   "Are you afraid of death? why or why not",
//   "Do you ever feel obligated to help your fellow human beings?",
//   "Are you capable of being faithful even when your lover is away for long periods of time",
//   "Do you think most people would prefer to be a lot more like you?",
//   "If you saw someone shoplifting, would you turn them in?",
//   "Did you ever shit your pants?",
//   "Would you strongly prefer to date someone of your own skin color / racial background?",
//   "Most of all, I want to meet someone who deserves MY: trust, loyalty, admiration or gratitude.",
//   "If you were going to have a child, would you want the other parent to be of the same ethnicity as you?",
//   "If you were in a long term relationship and your partner gained weight due to something like surgery recovery or childbirth, would you think less of them as a person?",
//   "Would you consider dating someone who dislikes children?",
//   "Your significant other's ex is coming into town and he/she wants to go out to dinner with them alone. How do you react?",
//   "Do you Google someone before a first date?",
//   "Your significant other is traveling and has the opportunity to stay with a good friend that you know they find to be very attractive. What's your stance on the situation?",
//   "How do you feel about falling in love?",
//   "Which makes for a better relationship? Passion and Discussion",
//   "How much can intelligence turn you on?",
//   "You're in a relationship/marriage and feel that you and your mate aren't having sex frequently enough. What do you do?",
//   "How important is it that a partner be capable of intelligent intercourse?",
//   "Ideally, how often would you have sex?",
//   "Would you ever change your religion (or adopt one) because your significant other wanted you to?",
//   "Would the world be a better place if people with low IQs were not allowed to reproduce?",
//   "If you had to name your greatest motivation in life thus far, what would it be? Love, Wealth, Expression, Knowledge",
//   "Rate your self-confidence: 1-5",
//   "Do you have a problem with racist jokes?", 
//   "If you don't do anything at all for an entire day, how does that make you feel?",
//   "What personality traits do you find most attractive?",
//   "Can you spend an entire month without me?",
//   "Would you rather cook for your significant other or cook as a couple?",
//   "Would you rather argue all night to resolve a conflict or end the argument unresolved before bed?",
//   "Would you rather be honest about something and hurt your partner, or keep a secret not to hurt them?",
//   "Would you rather have/have had a big wedding or elope?",
//   "Would you rather travel into the future or travel into the past together?",
//   "Would you rather cook for your partner or have them cook for you?",
//   "Would you rather be funnier than your partner or smarter?",
//   "Would you rather be with someone who is overly romantic or overly practical?",
//   "Would you rather receive a cheap thoughtful gift or a gift that cost a lot of money?",
//   "Would you rather stay in a relationship that wasn’t right or be single and happy?",
//   "How does your partner bring up uncomfortable topics?",
//   "Would you rather have a personal maid or a personal chef?",
//   "Would you rather have a clone of yourself or a clone of me?",
//   "Would you rather never gain weight from junk food or never get hangovers from drinking?",
//   "Would you rather be able to speak in any language or be able to talk to animals?",
//   "In a movie of your life, who would play each of the characters?",
//   "If you could make one legal thing illegal, what would it be?",
//   "What’s your favorite joke?",
// ]

export const questions = [
  "Should couples keep secrets?",
  "Is jealousy healthy in a relationship?",
  "Who do you think is more attractive- me or you?",
  "Describe how you are in bed in 3 words.",
  "If someone offered you a million dollars to leave me tonight, would you take it?",
  "Would you date someone who's ugly?",
  "Do you think your parents would approve if you and your partner got married?",
  "When was the first moment that you knew that you were attracted to me",
  "Change is a natural part of life, so what is it that has changed about me since we got together, and is it something you like?",
  "When we are in an argument or a serious discussion, do you ever just go ahead and apologize, not because you feel you are wrong, but because you just want the argument to end?",
  "We all have an ideal or dream partner. Do I give you everything, or almost everything, that you want or are searching for in a partner?",
  "If we had never gotten together, where do you think you’d be and how do you think your life would be right now?",
  "We all have relationship deal breakers, so what’s the one thing that would make you end our relationship?",
  "What is your absolute favorite thing for us to do together? And why that? ",
  "Would you ever want me to have cosmetic surgery or plastic surgery, and on what part of my body and why?",
  "Is your browsing history on your mobile phone something that you’d let me look at? Why or why not?",
  "Would you rather lose your sex organs or gain 100 pounds?",
  "Did you ever fart inside an elevator?",
  "What’s your biggest turn off in a person of the opposite sex?",
  "How would you spend an entire week without me?",
  "Which is your favorite color on me?",
  "Is there something that you love a lot, but you sacrificed just for me?",
  "What is one household chore that you hate to do?",
  "Were you ever on a blind date (not thru dating apps)?",
  "Which animal comes to your mind when you think of me?",
  "Rate the style of my dressing on a scale of 1 to 10.",
  "Name one thing that you just can’t give up even for me.",
  "What is your idea of a perfect marriage?",
  "Which of my friends do you like to talk to?",
  "Which is the most embarrassing show you are guilty of watching?",
  "Are you afraid of death? why or why not",
  "Would you leave me for a hotter and more beautiful girl?",
  "Do you ever feel obligated to help your fellow human beings?",
  "Are you capable of being faithful even when your lover is away for long periods of time",
  "Do you think most people would prefer to be a lot more like you?",
  "If you saw someone shoplifting, would you turn them in?",
  "Did you ever shit your pants?",
  "What attitude of mine turns you off?",
  "What do you tolerate about me?",
  "What is the best night or moment with me?",
  "Would you strongly prefer to date someone of your own skin color / racial background?",
  "Most of all, I want to meet someone who deserves MY: trust, loyalty, admiration or gratitude.",
  "If you were going to have a child, would you want the other parent to be of the same ethnicity as you?",
  "If you were in a long term relationship and your partner gained weight due to something like surgery recovery or childbirth, would you think less of them as a person?",
  "Would you consider dating someone who dislikes children?",
  "Your significant other's ex is coming into town and he/she wants to go out to dinner with them alone. How do you react?",
  "Do you Google someone before a first date?",
  "Your significant other is traveling and has the opportunity to stay with a good friend that you know they find to be very attractive. What's your stance on the situation?",
  "How do you feel about falling in love?",
  "Which makes for a better relationship? Passion or Discussion",
  "How much can intelligence turn you on?",
  "You're in a relationship/marriage and feel that you and your mate aren't having sex frequently enough. What do you do?",
  "How important is it that a partner be capable of intelligent intercourse?",
  "Ideally, how often would you have sex?",
  "Would you ever change your religion (or adopt one) because your significant other wanted you to?",
  "Would the world be a better place if people with low IQs were not allowed to reproduce?",
  "If you had to name your greatest motivation in life thus far, what would it be? Love, Wealth, Expression, Knowledge",
  "Rate your self-confidence: 1-5",
  "Do you have a problem with racist jokes?", 
  "If you don't do anything at all for an entire day, how does that make you feel?",
  "What personality traits do you find most attractive?",
  "Can you spend an entire month without me?",
  "Would you rather cook for your significant other or cook as a couple?",
  "Would you rather argue all night to resolve a conflict or end the argument unresolved before bed?",
  "Would you rather be honest about something and hurt your partner, or keep a secret not to hurt them?",
  "Would you rather have/have had a big wedding or elope?",
  "Would you rather travel into the future or travel into the past together?",
  "Would you rather cook for your partner or have them cook for you?",
  "Would you rather be funnier than your partner or smarter?",
  "Would you rather be with someone who is overly romantic or overly practical?",
  "Would you rather receive a cheap thoughtful gift or a gift that cost a lot of money?",
  "Would you rather stay in a relationship that wasn’t right or be single and happy?",
  "How does your partner bring up uncomfortable topics?",
  "Would you rather have a personal maid or a personal chef?",
  "Would you rather have a clone of yourself or a clone of me?",
  "Would you rather never gain weight from junk food or never get hangovers from drinking?",
  "Would you rather be able to speak in any language or be able to talk to animals?",
  "In a movie of your life, who would play each of the characters?",
  "If you could make one legal thing illegal, what would it be?",
  "What’s your favorite joke?",
]

export const howWell = [
  "What's your partner's favorite TV show?",
  "What food does your partner like to cook?",
  "What's your partner's favorite color?",
  "What does your partner do at work?",
  "What's your partner's favorite sex position?",
  "What is your partner's favorite food?",
  "What food does your partner hate?",
  "What is your partner's biggest pet peeve?",
  "What's something that always cheers their partner when they're sad?",
  "What did we do for our first date?",
  "What is the color of your partner's toothbrush?",
  "What is your partner's dream destination?",
  "What is your partner’s zodiac sign?",
  "How many siblings do they parents have?",
  "Does your partner have any nieces or nephews? If yes, how many? Can you name them?",
  "Is your partner religious? Is their family religious?",
  "Has he ever performed on stage?",
  "How many countries has your boyfriend traveled to? Did he travel alone?",
  "What is your partner’s favorite ice cream flavor?",
  "What is their favorite thing to eat for breakfast?",
  "Do they prefer spicy or bland foods?",
  "Do they like regular pizza or pineapple pizza?",
  "What can they not eat? What is he allergic to?",
  "What are the three things that they like about you?",
  "Where did you both take your first picture together?",
  "How many girlfriends/boyfriends did he have before you both got together?",
  "Which part of your body is your partner most attracted to?",
]

export const dares = [
  "For the next 5 minutes. Sing only instead of speaking",
  "Kiss your partner upside down like Mary Jane kissed Spiderman.",
  "Give your partner a 30-second lap dance.",
  "Suck on your partner's belly button.",
  "Take a sexy selfie and text it to me right now.",
  "Show your partner the part of your body that you think I find the sexiest.",
  "Read the newspaper in a romantic style",
  "Re-enact your favorite romantic scene",
  "Sing a lullaby beatboxing",
  "Call an old friend and talk gibberish",
  "Call your best friend and ask if he/she has stolen your watch",
  "Perform a stand-up comedy.",
  "Talk to Siri for 7 minutes without any interruption.",
  "Go shirtless",
  "Sing a romantic song dedicated to our relationship",
  "Freestyle rap about our relationship.",
  "Go live on any social media account and declare your love for me.",
  "Express your love in sign language.",
  "Write a poem about our love story",
  "Twerk at a boring song, till the music stops",
  "Dance on an imaginary pole.",
  "Spank yourself 5 times.",
  "Plank for 30 seconds, and while doing it, say one thing you love about me.",
  "Send a text to a random person by closing your eyes.",
]

export const mostLikely = [
"Who is more likely to wash the dishes?",
"Who is most likely to clean up after a party?",
"Who is most likely to drive on long trips?",
"Who is most likely to do the grocery shopping?",
'Who is most likely to cook?',
'Who is most likely to take out the trash?',
'Who is most likely to sleep in on a Sunday?',
'Who is most likely to make a big purchase?',
'Who is most likely to know the lyrics of every song ever written?',
'Who is most likely to say sorry first?',
'Who is most likely to dress up for Halloween?',
'Who is most likely to stay in and watch Netflix on a Friday night?',
'Who is most likely to strike up a conversation with a stranger?',
'Who is most likely to order dessert?',
'Who is most likely to give in and eat the last piece of pizza?',
'Who is most likely to eat the most in one sitting?',
'Who is most likely to stick up for themselves when they know they are right?',
'Who is most likely to give up on the argument?',
'Who is most likely to bring home a stray animal?',
'Who is most likely to stay up all night watching movies?',
'Who is most likely to quit their job?',
'Who is most likely to forget to eat all day?',
'Who is most likely to always have to stop to use the restroom?',
'Who is most likely to plan a trip?',
'Who is most likely to skip their morning routine and go right back to sleep?',
'Who is most likely to drink the whole bottle of wine on a Saturday night?',
'Who is more likely to make up after an argument first?',
'Who is most likely to be late?',
'Who is most likely to stay in their sweats all day?',
'Who is most likely to be the designated driver on a night out?',
'Who is most likely to put themselves before anyone else when it comes to taking care of others needs?',
'Who is more likely to find money in an old jacket pocket during spring cleaning season?',
'Who is more likely to do any housework that needs done around the home without being asked by someone else first?',
'Who will drop whatever they are doing just because you ask them for help with something important, but not urgent at that moment.',
'Who is most likely to have their phone run out of battery during the day?',
'Who is most likely to cry during a sad movie?',
'Who is most likely to eat most of the candy in your bowl when you are not looking?',
'Who is most likely to have dance parties by themselves when no one else is home?',
'Who is most likely to win an argument with their significant other over something ridiculous they both know neither of them care about that much, but just can’t admit it yet?',
'Who will be the first person up dancing at a party or club even though everyone else around them looks too cool for school and would never do anything like that?',
'Who is most likely to make up a new dance move to try out at the next party?',
'Who will most likely be first in line for all of the newest releases and can’t wait until they come out?',
'Who is most likely to take the most selfies when you go out somewhere?',
'Who will most likely be first in line at a concert to get up front and be able to touch their favorite band or singer?',
'Who is most likely to make everyone feel like they are part of something special, even if it’s just meeting for coffee with one other person who really needed someone positive and happy that day?',
'Who is most likely to remember your birthday without an app reminder?',
'Who is most likely to have a phone number from years ago because they never delete contacts no matter how long it’s been?',
'Who is most likely to give most of their belongings away before they move?',
'Who is most likely to be the first one dressed and ready for a party or event?',
'Who is most likely to forget your anniversary?',
'Who will do most of the talking when there are only two people in a room together?',
'Who is most likely to buy more wine for the weekend?',
'Who is most likely to skip delivery to save money?',
'Who is most likely to have a yard sale?',
'Who is most likely to be the designated driver for the night?',
'Who is most likely to fake a cold to skip work?',
'Who is most likely to call their parents every week?',
'Who is most likely to make the most money on a side job?',
'Who is most likely to start a business of their own?',
'Who is most likely to paint the house a different color?',
'Who is most likely to exercise each day?',
'Who is most likely to take most of their clothes to a consignment store?',
'Who is most likely to make the best coffee in the morning?',
'Who is most likely to go out with friends on Saturday night instead of staying home and relaxing?',
'Who is most likely to get a tattoo?',
'Who is most likely to fall asleep on the couch?',
'Who is most likely to skip brushing their teeth?',
'Who is most likely to get arrested?',
'Who is most likely to get a speeding ticket?',
'Who is most likely to save their money?',
'Who is most likely to go on a shopping spree?',
'Who is most likely to save ticket stubs as memories?',
'Who is most likely to plan date night?',
'Who is most likely to surprise the other with a gift?',
'Who is most likely to try to skip seeing their in laws?',
'Who is most likely to trip over air?',
'Who is most likely to get the hiccups?',
'Who is most likely to wear their shirt backwards?',
'Who is most likely to have the most followers on social media?',
'Who is most likely to go the longest without checking their phone?',
'Who is most likely to make the best cocktails for a party?',
'Who is most likely to pay full price instead of waiting for a sale?',
'Who is most likely to say “we can walk”?',
'Who is most likely to take their clothes for dry cleaning?',
'Who will be most likely to win an argument over which movie to watch tonight?',
'Who is most likely to get lost when they go on a new adventure with you?',
'Who is most likely to eat junk food all day?',
'Who is most likely to go on a diet?',
'Who is most likely to always be cold?',
'Who is most likely to go snowboarding?',
'Who is most likely to run in a triathlon?',
'Who is most likely to embarrass themselves?',
'Who is most likely to skip school?',
'Who is most likely to fall asleep first?',
'Who is most likely to be the last one out every time you go out for a night on the town?',
'Who will most likely want more food if we’re having guests over tonight?',
'Who is most likely to forget their wallet?',
'Who is most likely to ask to go on dates?',
'Who is most likely to be the best dressed person at a party?',
'Who is most likely to break something valuable?',
'Who will most likely make it home first from an after work happy hour with friends?',
'Who is most likely to give up their seat on a crowded bus or subway train for a woman or an older person?',
'Who is most likely to be the first one ready for a road trip and packed?',
'Who will most likely want to go out even though we’re both tired from work today?',
'Who is most likely to get lost while driving somewhere new?',
'Who is most likely to be most productive in the morning?',
'Who is most likely to get lost when we go on a road trip together?',
'Who is most likely to plan an event?',
'Who is most likely to make a big deal about things being organized or messy?',
'Who is most likely to eat more than their share of snacks at a party?',
'Who will most likely want to go to a party',
]